import VaultService from './vault.service';
import PromptService from './prompt.service';
import LLMService from './llm.service';
import SLMService from './slm.service';
import ApiService from './api.service';
import RegistryService from './registry.service';
import PlatformService from './platform.service';
import STSService from './sts.service';
import McpService from './mcp.service';
import VectorRagService from './vector-rag.service';
import GraphRagService from './graph-rag.service';
import WorkflowService from './workflow.service';
import ConnectorService from './connector.service';
import ExecutableFunctionService from './executable-function.service';
import VariableService from './variable.service';
import DatabaseService from './database.service';
import EmbeddingModelService from './embedding-model.service';
import ReRankingModelService from './reranking-model.service';
import AgentService from './agent.service';
import MessageBrokerService from './message-broker.service';
import GuardrailModelService from './guardrail-model.service';
import GuardrailService from './guardrail.service';
import GuardrailBindingService from './guardrail-binding.service';
import ScheduleTriggerService from './schedule-triggers.service';
import WebhookService from './webhook.service';
import UsageService from './usage.service';
import LineageService from './lineage.service';
import MetricsService from './metrics.service';

export const vaultService = new VaultService();
export const promptService = new PromptService();
export const llmService = new LLMService();
export const slmService = new SLMService();
export const apiService = new ApiService();
export const registryService = new RegistryService();
export const platformService = new PlatformService();
export const stsService = new STSService();
export const mcpService = new McpService();
export const vectorRagService = new VectorRagService();
export const graphRagService = new GraphRagService();
export const workflowService = new WorkflowService();
export const connectorService = new ConnectorService();
export const executableFunctionService = new ExecutableFunctionService();
export const variableService = new VariableService();
export const databaseService = new DatabaseService();
export const embeddingModelService = new EmbeddingModelService();
export const reRankingModelService = new ReRankingModelService();
export const agentService = new AgentService();
export const messageBrokerService = new MessageBrokerService();
export const guardrailModelService = new GuardrailModelService();
export const guardrailService = new GuardrailService();
export const guardrailBindingService = new GuardrailBindingService();
export const scheduleTriggerService = new ScheduleTriggerService();
export const webhookService = new WebhookService();
export const usageService = new UsageService();
export const lineageService = new LineageService();
export const metricsService = new MetricsService();
