export enum GuardrailSensitiveDataManagementModeType {
    EMPTY = '',
    USE_A_MODEL = 'USE_A_MODEL',
    USE_AN_API = 'USE_AN_API',
    USE_A_LLM = 'USE_A_LLM',
}

export enum GuardrailMaskingRuleType {
    EMPTY = '',
    NO_MASKING = 'NO_MASKING',
    MASK_FULLY = 'MASK_FULLY',
    MASK_PARTIALLY = 'MASK_PARTIALLY',
    REDACT = 'REDACT',
    DE_IDENTIFICATION = 'DE_IDENTIFICATION',
    REPLACE_WITH_ENTITY_TYPE = 'REPLACE_WITH_ENTITY_TYPE',
}

export enum GuardrailActionType {
    EMPTY = '',
    BLOCK = 'BLOCK',
    DETECT = 'DETECT',
}

export enum GuardrailApiConfigurationType {
    EMPTY = '',
    SENSITIVE_DATA_DETECTION = 'SENSITIVE_DATA_DETECTION',
    CONTENT_MODERATION = 'CONTENT_MODERATION',
    PROMPT_INJECTION_DETECTION = 'PROMPT_INJECTION_DETECTION',
    HALLUCINATION_PROTECTION = 'HALLUCINATION_PROTECTION',
}

export enum GuardrailApiProviderType {
    EMPTY = '',
    GOOGLE_DLP = 'GOOGLE_DLP',
    GUARDRAIL_AI = 'GUARDRAIL_AI',
    AMAZON_COMPREHEND = 'AMAZON_COMPREHEND',
    AZURE_AI_LANGUAGE = 'AZURE_AI_LANGUAGE',
    DETOXIFY_UNITORY_AI = 'DETOXIFY_UNITORY_AI',
    OPEN_AI_MODERATION = 'OPEN_AI_MODERATION',
    GOOGLE_PERSPECTIVE = 'GOOGLE_PERSPECTIVE',
    AZURE_AI_CONTENT_SAFETY = 'AZURE_AI_CONTENT_SAFETY',
}

export enum GuardrailModelProviderType {
    EMPTY = '',
    MICROSOFT_PRESIDIO = 'MICROSOFT_PRESIDIO',
    VERTEX_AI_CONTENT_MODERATION = 'VERTEX_AI_CONTENT_MODERATION',
    ANTHROPIC_CLAUDE_3 = 'ANTHROPIC_CLAUDE_3',
    GOOGLE_DEEPMIND_GEMINI = 'GOOGLE_DEEPMIND_GEMINI',
}

export enum GuardrailModelNameType {
    EMPTY = '',
    CONTENT_MODERATION = 'CONTENT_MODERATION',
    TEXT_MODERATION = 'TEXT_MODERATION',
    CLAUDE_3_OPUS = 'CLAUDE_3_OPUS',
    CLAUDE_3_SONNET = 'CLAUDE_3_SONNET',
    CLAUDE_3_HAIKU = 'CLAUDE_3_HAIKU',
    GEMINI_PRO = 'GEMINI_PRO',
    GEMINI_ULTRA = 'GEMINI_ULTRA',
}

export enum GuardrailModelInputType {
    ANALYZER_SERVICE_HOST = 'ANALYZER_SERVICE_HOST',
    ANONYMIZER_SERVICE_HOST = 'ANONYMIZER_SERVICE_HOST',
    API_KEY = 'API_KEY',
    PROJECT_ID = 'PROJECT_ID',
    LOCATION = 'LOCATION',
    MODEL_NAME = 'MODEL_NAME',
    AUTHENTICATION_TYPE = 'AUTHENTICATION_TYPE',
    TOKEN = 'TOKEN',
    BASE_URL = 'BASE_URL',
}

export enum SensitiveDataType {
    NAME = 'PERSON',
    PHONE_NUMBER = 'PHONE_NUMBER',
    EMAIL = 'EMAIL_ADDRESS',
    ADDRESS = 'LOCATION',
    DRIVER_ID = 'US_DRIVER_LICENSE',
    PASSPORT_NUMBER = 'US_PASSPORT',
    SSN = 'US_SSN',
    TIN = 'US_ITIN',
    CREDIT_CARD = 'CREDIT_CARD',
    BANK_ACCOUNT_NUMBER = 'US_BANK_NUMBER',
    IBAN_CODE = 'IBAN_CODE',
    IPV4_ADDRESS = 'IP_ADDRESS',
    URLS = 'URL',
}

export enum ClassificationType {
    GENERAL = 'General',
    FINANCIAL = 'Financial',
    IT = 'IT',
}

export enum GuardrailBindingLevelType {
    WORKSPACE = 'workspace',
    WORKFLOW = 'workflow',
    AGENT = 'agent',
}
