export enum UsageType {
    PLATFORM_USAGE = 'PLATFORM_USAGE',
    STORAGE = 'STORAGE',
    TOKENS = 'TOKENS',
    CREDITS = 'CREDITS',
    WORKFLOW_EXECUTIONS = 'WORKFLOW_EXECUTIONS',
}

export enum DynamicQueryType {
    PLATFORM_USAGE_SUMMERY_BY_DATE_RANGE = 'PLATFORM_USAGE_SUMMERY_BY_DATE_RANGE',
    WORKSPACE_MONTHLY_STORAGE_USAGE = 'WORKSPACE_MONTHLY_STORAGE_USAGE',
    WORKSPACE_CREDIT_USAGE_BY_DATE_RANGE = 'WORKSPACE_CREDIT_USAGE_BY_DATE_RANGE',
    WORKSPACE_MONTHLY_CREDIT_USAGE = 'WORKSPACE_MONTHLY_CREDIT_USAGE',
    WORKSPACE_MONTHLY_TOKEN_USAGE = 'WORKSPACE_MONTHLY_TOKEN_USAGE',
    WORKSPACE_TOKEN_USAGE_BY_DATE_RANGE = 'WORKSPACE_TOKEN_USAGE_BY_DATE_RANGE',
    WORKSPACE_WORKFLOW_EXECUTIONS_BY_DATE_RANGE = 'WORKSPACE_WORKFLOW_EXECUTIONS_BY_DATE_RANGE',
    MAXIMUM_USAGE = 'MAXIMUM_USAGE',
    WORKFLOW_EXECUTION_SUMMARY = 'WORKFLOW_EXECUTION_SUMMARY',
    LLM_EXECUTION_SUMMARY = 'LLM_EXECUTION_SUMMARY',
    SLM_EXECUTION_SUMMARY = 'SLM_EXECUTION_SUMMARY',
    API_EXECUTION_SUMMARY = 'API_EXECUTION_SUMMARY',
    RECENT_ACTIVITY = 'RECENT_ACTIVITY',
}
