import { IFeedbackLearning } from '@/models';

export const mock_learnings: IFeedbackLearning[] = [
    {
        id: 'fb-1',
        feedback: 'The assistant should use more professional tone when replying to emails.',
        workflowId: 'wf-4',
        sessionId: 'sess-101',
        agentId: 'agent-1',
        agentName: 'Email Assistant',
        metadata: {
            tags: ['professionalism', 'tone'],
            category: 'Communication Style',
            reviewed_by: 'John Doe',
        },
        rationale: 'User mentioned the previous reply was too casual.',
        type: 'General',
        isActive: true,
        isDeleted: false,
        createdAt: '2024-03-10T10:00:00Z',
        updatedAt: '2024-03-10T10:00:00Z',
        isReadOnly: false,
        feedbackStatus: 'Pending',
        groupItems: [],
        canAuthor: true,
        supportingFile: [],
    },
    {
        id: 'fb-2',
        feedback: 'Avoid using technical jargon in customer support interactions.',
        workflowId: 'wf-1',
        sessionId: 'sess-202',
        agentId: 'agent-2',
        agentName: 'Support Bot',
        metadata: {
            tags: ['clarity', 'jargon'],
            category: 'Guideline',
            reviewed_by: 'Jane Smith',
        },
        rationale: 'Customers were confused by terms like "latency" and "payload".',
        type: 'Constraint',
        isActive: true,
        isDeleted: false,
        createdAt: '2024-03-15T14:30:00Z',
        updatedAt: '2024-03-15T14:30:00Z',
        isReadOnly: false,
        feedbackStatus: 'Approved',
        groupItems: [],
        canAuthor: true,
        supportingFile: [],
    },
    {
        id: 'fb-3',
        feedback: 'Always ask for clarification if the input is ambiguous.',
        workflowId: 'wf-1',
        sessionId: 'sess-203',
        agentId: 'agent-2',
        agentName: 'Support Bot',
        metadata: {
            tags: ['accuracy', 'best-practice'],
            category: 'Standard Operating Procedure',
        },
        rationale: 'Prevent cases where the bot assumes the wrong customer need.',
        type: 'Instruction',
        isActive: true,
        isDeleted: false,
        createdAt: '2024-03-16T09:15:00Z',
        updatedAt: '2024-03-16T09:15:00Z',
        isReadOnly: false,
        feedbackStatus: 'Pending',
        groupItems: [],
        canAuthor: true,
        supportingFile: [],
    },
];

export const mock_workflow_details: Record<string, { id: string, name: string }> = {
    'wf-1': {
        id: 'wf-1',
        name: 'Customer Support Bot',
    },
    'wf-4': {
        id: 'wf-4',
        name: 'Email Summarizer',
    },
};
